spring:
  datasource:
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    platform: mysql
    username: root
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  main:
    allow-bean-definition-overriding: true
qwan:
  web:
    global:
      response:
        whitelist:
        enabled: true
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.app.maggite.starter.domain
